version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://ble_user:ble_password@db:5432/ble_scanner
    depends_on:
      - db
    volumes:
      - ./logs:/app/logs
      - /var/run/dbus:/var/run/dbus:ro
    devices:
      - /dev/bus/usb:/dev/bus/usb
    network_mode: host
    privileged: true
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=ble_scanner
      - POSTGRES_USER=ble_user
      - POSTGRES_PASSWORD=ble_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: